name: Unity build & deployment

on:
  push:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: UnityCache
          restore-keys: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.0
        with:
          unityVersion: 2019.3.14f1
          targetPlatform: WebGL
          allowDirtyBuild: true

      # Deploy to GitHub Pages
      - name: Copy workflows, README, etc.
        run: |
          sudo cp ./CNAME ./build/WebGL/WebGL/CNAME || echo "No CNAME"
          sudo cp ./README.md ./build/WebGL/WebGL/README.md || echo "No README.md"
          sudo cp ./LICENSE ./build/WebGL/WebGL/LICENSE || echo "No LICENSE"
          sudo cp ./.gitattributes ./build/WebGL/WebGL/.gitattributes || echo "No .gitattributes"

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./build/WebGL/WebGL/
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ftp-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          ref: 'gh-pages'

      # FTP Deploy
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://xr-solutions.nl/
          ftp-username: github-accessiblity@xr-solutions.nl
          ftp-password: ${{ secrets.FTP_PASSWORD }}
